// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  appSidebar: [{ type: "autogenerated", dirName: "." }],
  javascriptSidebar: [{ type: "autogenerated", dirName: "javascript" }],
};

module.exports = sidebars;
